### ISSUE TITLE
Move scss imports to *.page.js files

### ISSUE THREAD

**Issue by nerik** [Vizzuality/TRASE-frontend#75]
This way we allow webpack code splitting/chunks to properly work. See factsheets.scss for an example of what needs to be moved.
Additionally this allows us to benefit from webpack file aliasing.

**Comment by agnlez** [comment]
In my opinion, pages shouldn't be treated as components because they aren't. If you want to move them because we already doing it, it's fine. You talked about importing `_base.scss` in GFW (actually it's not a good example...) but here you are importing `_settings`, so in the end it's the same but different file.

Anyway modularity has never gotten along with CSS structure.

**Comment by nerik** [comment]
This is debatable, but the webpack argument stays.
Let's have a conversation with Clement about this after the deadline :)
